services:
  nginx:
    image: nginx:latest
    # privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      # - ./nginx/certs/digonto.in/:/etc/letsencrypt/live/digonto.in/:ro
      - /etc/letsencrypt/archive/digonto.in/:/etc/letsencrypt/live/digonto.in/:ro
    depends_on:
      - web
  web:
    image: 953253449063.dkr.ecr.us-west-2.amazonaws.com/digonto/web:latest
    environment:
      PORT: 3000
    ports:
      - 3000:3000


# volumes:
