services:
  gateway:
    environment:
      NODE_ENV: dev
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
      target: dev
    ports:
      - 3000:3000
    environment:
      NODE_ENV: dev
      PORT: 3000
    volumes:
      - ./web:/usr/src/app/
      - ./packages/:/usr/src/packages/
      - web-nodemodules:/usr/src/app/node_modules
    depends_on:
      - gateway
  nginx:
    build:
      context: nginx
    ports:
      - 8080:80
    depends_on:
      - web
      - gateway
