version: '3'
services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      PORT: 4000
    volumes:
      - ./gateway/:/app/
      - ./packages/:/packages/
      - gateway-nodemodules:/app/node_modules
    depends_on:
      - postgres

volumes:
  gateway-nodemodules: {}
  gateway-dist: {}
  web-nodemodules: {}
  pgdata: {}
