services:
  gateway:
    build:
      target: citest
    environment:
      NODE_ENV: ci
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  web:
    build:
      target: dev
    environment:
      NODE_ENV: test