version: '3'
services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  gateway:
    build:
      context: gateway
    environment:
      PORT: 4000
    volumes:
      - ./gateway/:/app/
      - gateway-nodemodules:/app/node_modules
    depends_on:
      - postgres
  web:
    build:
      context: web
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    volumes:
      - ./web:/app/
      - web-nodemodules:/app/node_modules
    depends_on:
      - gateway
  nginx:
    build:
      context: nginx
    ports:
      - 8080:80
    depends_on:
      - web
      - gateway

volumes:
  gateway-nodemodules: {}
  gateway-dist: {}
  web-nodemodules: {}
  pgdata: {}
