apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
    - name: tcp-http
      protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port
      nodePort: 30001 # external port
    - name: tcp-https
      protocol: TCP
      port: 443
      nodePort: 30002
    - name: udp-http
      protocol: UDP
      port: 80
      nodePort: 30001
    - name: udp-https
      protocol: UDP
      port: 443
      nodePort: 30002
  selector:
    app: nginx
