version: '3'
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_PASSWORD: 123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  gateway:
    build:
      context: .
      target: test
    ports:
      - 4000:4000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: test
      PORT: 4000
      NODE_ENV: ci
    volumes:
      - .:/app/
      - gateway-nodemodules:/app/node_modules
      - gateway-dist:/app/dist
    depends_on:
      - postgres

volumes:
  gateway-nodemodules: {}
  gateway-dist: {}
  pgdata: {}
