apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-depl
  namespace: digonto
spec:
  template:
    metadata:
      name: web-pod
      labels:
        app: web
    spec:
      containers:
        - name: web
          #image: nginx
          image: 953253449063.dkr.ecr.ap-south-1.amazonaws.com/digonto-web
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: web
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

---
apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - targetPort: 3000
      port: 3000
      nodePort: 30010
