---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: digonto-listener-80
  namespace: digonto
spec:
  port: 80
  protocol: HTTP
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF
---
apiVersion: getambassador.io/v3alpha1
kind: Listener
metadata:
  name: digonto-listener-443
  namespace: ambassador
spec:
  port: 443
  protocol: HTTPS
  securityModel: XFP
  hostBinding:
    namespace:
      from: SELF
