apiVersion: v1
kind: Service
metadata:
  name: web-cip
  namespace: digonto
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  #type: ClusterIP
  selector:
    app: web
  ports:
    - targetPort: 80
      port: 80
      #nodePort: 30010
