name: Run Tests
run-name: Build Workflow running for ${{ github.event_name }} on ${{ github.ref }}
on: [push]

env:
  WEB_REPO_URL: 953253449063.dkr.ecr.ap-south-1.amazonaws.com/digonto/web
  GATEWAY_REPO_URL: 953253449063.dkr.ecr.ap-south-1.amazonaws.com/digonto/gateway


jobs:
  web_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Web
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          push: false
          tags: digonto.in/web-test:latest
          target: test
          no-cache: true

  gateway_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Gateway
        run: docker compose -f ./gateway/compose.ci.yaml up --build --exit-code-from gateway

  build-upload:
    needs: [web_test, gateway_test]
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::953253449063:role/digonto-github-role
          role-session-name: GitHubActionsDigonto

      - name: Log AWS STS Info
        run: aws sts get-caller-identity

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./web
          file: ./web/Dockerfile
          push: true
          tags: |
            ${{ env.WEB_REPO_URL }}:${{ github.sha }}
          platforms: linux/amd64
          target: prod
          no-cache: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          file: ./gateway/Dockerfile
          push: true
          tags: |
            ${{ env.GATEWAY_REPO_URL }}:${{ github.sha }}
          platforms: linux/amd64
          target: prod
          no-cache: true