name: Deploy Workflow
run-name: Production Deploy Workflow running for ${{ github.event.workflow_run.event }} on ${{ github.ref }}
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed
jobs:
  production-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::953253449063:role/digonto-github-role
          role-session-name: GitHubActionsDigonto

      - run: aws sts get-caller-identity
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      # Login to ecr
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: ./digonto.in/web
#          file: ./digonto.in/web/Dockerfile
#          push: false
#          tags: digonto.in/web:latest
#          target: prod
#          no-cache: true
