name: Deploy Workflow
run-name: Production Deploy Workflow running for ${{ github.event.workflow_run.event }} on ${{ github.ref }}
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed
env:
  ECR_REPO_URL: 953253449063.dkr.ecr.ap-south-1.amazonaws.com/digonto-web

jobs:
  production-deploy:
    permissions:
      id-token: write
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::953253449063:role/digonto-github-role
          role-session-name: GitHubActionsDigonto

      - name: Log AWS STS Info
        run: aws sts get-caller-identity

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./digonto.in/web
          file: ./digonto.in/web/Dockerfile
          push: true
          tags: |
            ${{ env.ECR_REPO_URL }}:${{ github.sha }}
          platforms: linux/amd64
          target: prod
          no-cache: true

      - name: Remove 'latest' tag
        run: aws ecr batch-delete-image --repository-name digonto-web --image-ids imageTag=latest --region ap-south-1

      - name: Retag Image
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name digonto-web --image-ids imageTag=${{ github.sha }} --region ap-south-1 --output json | jq --raw-output '.images[].imageManifest')
          aws ecr put-image --repository-name digonto-web --image-tag latest --image-manifest "$MANIFEST"
          echo $MANIFEST

      - name: Describe Image
        run: aws ecr describe-images --repository-name digonto-web
